// Données spécifiques à la carte "Inu - Chien Loup Tchécoslovaque"

const cardData = {
    "@context": "https://schema.org/",
    "@type": "Taxon",
    "deck_emoji": "🐾",
    "scientificName": "Canis lupus familiaris",
    "images": [
        "assets/images/image_01.jpg",
        "assets/images/image_02.jpg",
        "assets/images/image_03.jpg",
        "assets/images/image_04.jpg"
    ],
    "name_i18n": { "fr": "Inu (Chien Loup Tchécoslovaque)", "en": "Inu (Czechoslovakian Wolfdog)", "es": "Inu (Perro Lobo Checoslovaco)", "zh": "Inu (捷克斯洛伐克狼犬)", "hi": "इनु (चेकोस्लोवाकियन वुल्फडॉग)", "ar": "إينو (كلب الذئب التشيكوسلوفاكي)", "pt": "Inu (Cão-lobo-checoslovaco)", "ru": "Ину (Чехословацкий влчак)", "ja": "イヌ（チェコスロバキアン・ウルフドッグ）", "de": "Inu (Tschechoslowakischer Wolfhund)" },
    "description_i18n": { "fr": "Une race récente issue d'un croisement entre un Berger Allemand et un loup des Carpates. Il combine la robustesse du loup et la sociabilité du chien, mais demande un maître expérimenté.", "en": "A recent breed resulting from a cross between a German Shepherd and a Carpathian wolf. It combines the robustness of the wolf and the sociability of the dog, but requires an experienced owner.", "es": "Una raza reciente resultante de un cruce entre un pastor alemán y un lobo de los Cárpatos. Combina la robustez del lobo y la sociabilidad del perro, pero requiere un dueño experimentado.", "zh": "一个最近的品种，由德国牧羊犬和喀尔巴阡狼杂交而成。它结合了狼的强壮和狗的社交性，但需要有经验的主人。", "hi": "यह एक हालिया नस्ल है जो जर्मन शेफर्ड और कार्पेथियन भेड़िये के बीच क्रॉस से उत्पन्न हुई है। यह भेड़िये की मजबूती और कुत्ते की सामाजिकता को जोड़ती है, लेकिन इसके लिए एक अनुभवी मालिक की आवश्यकता होती है।", "ar": "سلالة حديثة ناتجة عن تزاوج بين كلب الراعي الألماني وذئب الكاربات. تجمع بين قوة الذئب واجتماعية الكلب، ولكنها تتطلب مالكًا خبيرًا.", "pt": "Uma raça recente resultante de um cruzamento entre um Pastor Alemão e um lobo dos Cárpatos. Combina a robustez do lobo e a sociabilidade do cão, mas requer um dono experiente.", "ru": "Недавняя порода, полученная в результате скрещивания немецкой овчарки и карпатского волка. Она сочетает в себе выносливость волка и общительность собаки, но требует опытного владельца.", "ja": "ジャーマン・シェパードとカルパティアオオカミの交配によって生まれた最近の犬種。オオカミの頑丈さと犬の社交性を兼ね備えていますが、経験豊富な飼い主が必要です。", "de": "Eine neue Rasse, die aus einer Kreuzung zwischen einem Deutschen Schäferhund und einem Karpatenwolf hervorgegangen ist. Sie vereint die Robustheit des Wolfs und die Geselligkeit des Hundes, erfordert aber einen erfahrenen Besitzer." },
    "fun_facts_i18n": { "fr": ["Créée à l'origine pour des opérations militaires dans les années 50.", "Conserve un fort instinct de meute et est très loyal envers sa 'famille'.", "Peut être très méfiant envers les étrangers, agissant comme un excellent gardien."], "en": ["Originally created for military operations in the 1950s.", "Retains a strong pack instinct and is very loyal to its 'family'.", "Can be very wary of strangers, acting as an excellent guardian."], "es": ["Creado originalmente para operaciones militares en la década de 1950.", "Conserva un fuerte instinto de manada y es muy leal a su 'familia'.", "Puede ser muy desconfiado con los extraños, actuando como un excelente guardián."], "zh": ["最初是为1950年代的军事行动而创建的。", "保留了强烈的群体本能，对它的“家庭”非常忠诚。", "对陌生人可能非常警惕，是出色的看守者。"], "hi": ["मूल रूप से 1950 के दशक में सैन्य अभियानों के लिए बनाया गया था।", "यह एक मजबूत झुंड वृत्ति रखता है और अपने 'परिवार' के प्रति बहुत वफादार होता है।", "यह अजनबियों से बहुत सावधान रह सकता है, एक उत्कृष्ट संरक्षक के रूप में कार्य करता है।"], "ar": ["تم إنشاؤه في الأصل للعمليات العسكرية في الخمسينيات.", "يحتفظ بغريزة قطيع قوية وهو مخلص جدًا لـ 'عائلته'.", "يمكن أن يكون حذرًا جدًا من الغرباء، ويعمل كحارس ممتاز."], "pt": ["Originalmente criado para operações militares na década de 1950.", "Mantém um forte instinto de matilha e é muito leal à sua 'família'.", "Pode ser muito desconfiado com estranhos, atuando como um excelente guardião."], "ru": ["Первоначально был создан для военных операций в 1950-х годах.", "Сохраняет сильный стайный инстинкт и очень предан своей 'семье'.", "Может быть очень настороженным по отношению к незнакомцам, выступая в роли отличного охранника."], "ja": ["元々は1950年代に軍事作戦のために作られました。", "強い群れの習性を保持しており、その「家族」に対して非常に忠実です。", "見知らぬ人には非常に警戒心が強く、優れた番犬として行動します。"], "de": ["Ursprünglich für Militäreinsätze in den 1950er Jahren geschaffen.", "Behält einen starken Rudelinstinkt bei und ist seiner 'Familie' gegenüber sehr loyal.", "Kann Fremden gegenüber sehr misstrauisch sein und fungiert als ausgezeichneter Wächter."] },
    "monologue_i18n": {
        "fr": "Bon, Majesté, assieds-toi, le Bourdon a des choses à dire sur ton Inu. Ce n'est pas n'importe quel toutou, c'est un Chien Loup Tchécoslovaque. Moitié chien de berger obéissant, moitié loup des Carpates sauvage. Un cocktail... intéressant. Faut savoir qu'à la base, c'était un projet militaire. Pas étonnant qu'il soit robuste ! Côté stats, on est sur du solide : 65 centimètres pour 29 kilos de muscles. Mais oublie la vitesse dans les airs, il ne vole pas mieux que moi après un bon repas. Par contre, avec 45 km/h au sol, il te sème facile. Ce qui est fascinant, c'est son caractère. Il est incroyablement loyal avec sa meute – c'est-à-dire toi – mais garde une méfiance de loup envers les inconnus. C'est un gardien né ! Par contre, attention, son instinct de prédateur est bien réel, donc les petits animaux, c'est pas son truc. C'est une machine complexe qui vit une bonne quinzaine d'années, un vrai compagnon de vie, à condition de savoir qui est le chef. Et le chef, Majesté, c'est toi. Allez, maintenant que je t'ai tout dit, voyons si t'as bien écouté. Quiz time !",
        "en": "Alright, your Majesty, take a seat, the Bourdon has things to say about your Inu. This isn't just any doggy; it's a Czechoslovakian Wolfdog. Half obedient German Shepherd, half wild Carpathian wolf. An... interesting cocktail. You should know it was originally a military project. No wonder it's sturdy! Stat-wise, we're talking solid numbers: 65 centimeters and 29 kilos of muscle. But forget about air speed; it flies no better than I do after a big meal. On the ground, though, at 45 km/h, it'll leave you in the dust. What's fascinating is its personality. It's incredibly loyal to its pack—that means you—but keeps a wolf's wariness of strangers. A born guardian! Be warned, though, its predatory instinct is very real, so small pets are not its thing. It's a complex machine that lives a good 15 years, a true life companion, provided you know who's boss. And the boss, your Majesty, is you. Now that I've told you everything, let's see if you were listening. Quiz time!",
        "es": "Bueno, Majestad, siéntate, que el Bourdon tiene cosas que contarte sobre tu Inu. No es un perrito cualquiera, es un Perro Lobo Checoslovaco. Mitad Pastor Alemán obediente, mitad lobo salvaje de los Cárpatos. Un cóctel... interesante. Debes saber que originalmente fue un proyecto militar. ¡Con razón es tan robusto! En cuanto a estadísticas, son sólidas: 65 centímetros y 29 kilos de músculo. Pero olvídate de la velocidad en el aire, no vuela mejor que yo después de una buena comida. En tierra, sin embargo, a 45 km/h, te deja atrás fácilmente. Lo fascinante es su carácter. Es increíblemente leal a su manada —o sea, a ti— pero mantiene la desconfianza de un lobo hacia los extraños. ¡Es un guardián nato! Pero ojo, su instinto depredador es muy real, así que los animales pequeños no son lo suyo. Es una máquina compleja que vive unos buenos 15 años, un verdadero compañero de vida, siempre que sepas quién manda. Y el que manda, Majestad, eres tú. Ahora que te lo he contado todo, veamos si has escuchado. ¡Hora del quiz!",
        "zh": "好吧，陛下，坐好，你忠诚的仆人本大黄蜂要来汇报一下你的“犬”了。这可不是普通的狗狗，是捷克斯洛伐ك狼犬。一半是服从的德国牧羊犬，一半是野性的喀尔巴阡狼。一个……很有趣的组合。你要知道，它最初是个军事项目。难怪这么结实！数据方面，也很扎实：身高65厘米，体重29公斤的肌肉。但别指望它能飞，它飞得可不比我饱餐一顿后好多少。不过在陆地上，时速45公里，能把你远远甩在后面。最迷人的是它的性格。它对它的“狼群”——也就是你——极其忠诚，但对陌生人保持着狼的警惕。天生的守护者！不过要小心，它的捕食本能是真实存在的，所以小宠物可不是它的朋友。这是一个能活15年的复杂机器，一个真正的生活伴侣，前提是你得让它知道谁是老大。而老大，陛下，就是您。好了，我把该说的都说了，看看你有没有在听。测验时间！",
        "hi": "ठीक है, महाराज, बैठ जाइए, Bourdon को आपके इनु के बारे में कुछ बताना है। यह कोई साधारण कुत्ता नहीं है; यह एक चेकोस्लोवाकियन वुल्फडॉग है। आधा आज्ञाकारी जर्मन शेफर्ड, आधा जंगली कार्पेथियन भेड़िया। एक... दिलचस्प मिश्रण। आपको पता होना चाहिए कि यह मूल रूप से एक सैन्य परियोजना थी। कोई आश्चर्य नहीं कि यह इतना मजबूत है! आंकड़ों की बात करें तो, हम ठोस संख्या की बात कर रहे हैं: 65 सेंटीमीटर और 29 किलो मांसपेशियां। लेकिन हवा में गति को भूल जाइए; यह एक बड़े भोजन के बाद मुझसे बेहतर नहीं उड़ता। हालांकि, जमीन पर 45 किमी/घंटा की रफ्तार से यह आपको धूल चटा देगा। जो आकर्षक है वह है इसका व्यक्तित्व। यह अपने झुंड - यानी आपके - के प्रति अविश्वसनीय रूप से वफादार है, लेकिन अजनबियों के प्रति भेड़िये जैसी सतर्कता रखता है। एक जन्मजात संरक्षक! हालांकि, सावधान रहें, इसकी शिकारी प्रवृत्ति बहुत वास्तविक है, इसलिए छोटे पालतू जानवर इसके लिए नहीं हैं। यह एक जटिल मशीन है जो 15 साल तक जीवित रहती है, एक सच्चा जीवन साथी, बशर्ते आप जानते हों कि बॉस कौन है। और बॉस, महाराज, आप हैं। अब जब मैंने आपको सब कुछ बता दिया है, तो देखते हैं कि क्या आप सुन रहे थे। प्रश्नोत्तरी का समय!",
        "ar": "حسناً يا جلالة الملك، تفضل بالجلوس، فلدى بوردون ما يقوله عن كلبك إينو. هذا ليس مجرد كلب عادي، إنه كلب الذئب التشيكوسلوفاكي. نصفه راعٍ ألماني مطيع، ونصفه ذئب كارباتي بري. مزيج... مثير للاهتمام. يجب أن تعلم أنه كان في الأصل مشروعًا عسكريًا. لا عجب أنه قوي! من ناحية الإحصائيات، نتحدث عن أرقام قوية: 65 سنتيمترًا و 29 كيلوجرامًا من العضلات. لكن انسَ سرعته في الهواء، فهو لا يطير أفضل مني بعد وجبة دسمة. أما على الأرض، فبسرعة 45 كم/ساعة، سيسبقك بسهولة. المثير للإعجاب هو شخصيته. إنه مخلص للغاية لقطيعه - أي أنت - لكنه يحتفظ بحذر الذئب من الغرباء. حارس بالفطرة! لكن احذر، غريزة الافتراس لديه حقيقية جدًا، لذا فالحيوانات الأليفة الصغيرة ليست من شأنه. إنه آلة معقدة تعيش 15 عامًا، رفيق حياة حقيقي، شريطة أن تعرف من هو القائد. والقائد، يا جلالة الملك، هو أنت. الآن بعد أن أخبرتك بكل شيء، دعنا نرى ما إذا كنت تستمع. وقت الاختبار!",
        "pt": "Muito bem, Vossa Majestade, sente-se, que o Bourdon tem coisas a dizer sobre o seu Inu. Este não é um cão qualquer; é um Cão-lobo-checoslovaco. Metade Pastor Alemão obediente, metade lobo selvagem dos Cárpatos. Um cocktail... interessante. Deve saber que foi originalmente um projeto militar. Não admira que seja robusto! Em termos de estatísticas, estamos a falar de números sólidos: 65 centímetros e 29 quilos de músculo. Mas esqueça a velocidade no ar; não voa melhor do que eu depois de uma grande refeição. No entanto, em terra, a 45 km/h, deixa-o para trás. O que é fascinante é a sua personalidade. É incrivelmente leal à sua matilha - ou seja, a si - mas mantém a desconfiança de um lobo para com estranhos. Um guardião nato! Mas atenção, o seu instinto de predação é bem real, por isso animais de estimação pequenos não são para ele. É uma máquina complexa que vive uns bons 15 anos, um verdadeiro companheiro de vida, desde que saiba quem é o chefe. E o chefe, Vossa Majestade, é você. Agora que já lhe disse tudo, vamos ver se esteve a ouvir. Hora do quiz!",
        "ru": "Итак, Ваше Величество, присаживайтесь, Бурдону есть что сказать о вашем Ину. Это не просто какая-то собачка, это Чехословацкий влчак. Наполовину послушная немецкая овчарка, наполовину дикий карпатский волк. Интересный... коктейль. Знайте, изначально это был военный проект. Неудивительно, что он такой крепкий! Что касается статов, то тут все солидно: 65 сантиметров и 29 килограммов мышц. Но забудьте о скорости в воздухе, он летает не лучше, чем я после плотного обеда. Зато на земле, со скоростью 45 км/ч, он легко оставит вас позади. Что fascinant, так это его характер. Он невероятно предан своей стае — то есть вам — но сохраняет волчью настороженность к незнакомцам. Прирожденный страж! Однако, будьте осторожны, его хищнический инстинкт вполне реален, так что мелкие домашние животные — не его тема. Это сложная машина, которая живет добрых 15 лет, настоящий спутник жизни, при условии, что вы знаете, кто здесь главный. А главный, Ваше Величество, это вы. Теперь, когда я все рассказал, посмотрим, слушали ли вы. Время викторины!",
        "ja": "さて、陛下、腰をお掛けください。あなたのイヌについて、このブルドンが仕入れた情報をお話しします。これはただの犬ではありません。チェコスロバキアン・ウルフドッグです。半分は従順なジャーマン・シェパード、半分は野生のカルパティアオオカミ。実に…興味深いカクテルですね。元々は軍事プロジェクトだったんですよ。頑丈なのも頷けます。ステータスも優秀で、体高65センチ、体重29キロの筋肉質。でも空中での速さは忘れましょう。満腹の私よりうまく飛べませんから。しかし地上では時速45キロで、あなたをあっという間に置き去りにします。魅力的なのはその性格。群れ、つまりあなたには非常に忠実ですが、見知らぬ人には狼のような警戒心を保ちます。生まれながらの番犬です！ただし、捕食本能は本物なので、小動物は苦手です。約15年生きる複雑な機械、真の生涯の伴侶ですが、そのためには誰がボスかを知らしめる必要があります。そして陛下、ボスはあなたです。さあ、全てお話ししましたから、ちゃんと聞いていたか試させてもらいましょう。クイズの時間です！",
        "de": "Also, Majestät, setzen Sie sich, der Bourdon hat etwas über Ihren Inu zu sagen. Das ist nicht irgendein Hündchen; es ist ein Tschechoslowakischer Wolfhund. Halb gehorsamer Deutscher Schäferhund, halb wilder Karpatenwolf. Ein... interessanter Cocktail. Sie sollten wissen, dass es ursprünglich ein Militärprojekt war. Kein Wunder, dass er so robust ist! Was die Werte angeht, sprechen wir von soliden Zahlen: 65 Zentimeter und 29 Kilo Muskeln. Aber vergessen Sie die Geschwindigkeit in der Luft; er fliegt nicht besser als ich nach einer großen Mahlzeit. Am Boden lässt er Sie mit 45 km/h jedoch locker hinter sich. Faszinierend ist seine Persönlichkeit. Er ist unglaublich loyal gegenüber seinem Rudel – also Ihnen – behält aber die wolfstypische Vorsicht gegenüber Fremden. Ein geborener Wächter! Aber Vorsicht, sein Jagdinstinkt ist sehr real, kleine Haustiere sind also nicht sein Ding. Er ist eine komplexe Maschine, die gut 15 Jahre lebt, ein wahrer Lebensgefährte, vorausgesetzt, Sie wissen, wer der Boss ist. Und der Boss, Majestät, sind Sie. Nun, da ich Ihnen alles erzählt habe, wollen wir sehen, ob Sie zugehört haben. Quizzeit!"
    },
    "stats_i18n": {
        "taille": { "emoji": "📏", "label": { "fr": "TAILLE", "en": "SIZE", "es": "TAMAÑO", "zh": "尺寸", "hi": "आकार", "ar": "الحجم", "pt": "TAMANHO", "ru": "РАЗМЕР", "ja": "サイズ", "de": "GRÖSSE" }, "value": 0.65, "unit": "m" },
        "poids": { "emoji": "⚖️", "label": { "fr": "POIDS", "en": "WEIGHT", "es": "PESO", "zh": "重量", "hi": "वज़न", "ar": "الوزن", "pt": "PESO", "ru": "ВЕС", "ja": "重量", "de": "GEWICHT" }, "value": 29, "unit": "kg" },
        "longevite": { "emoji": "⏳", "label": { "fr": "LONGÉVITÉ", "en": "LIFESPAN", "es": "LONGEVIDAD", "zh": "寿命", "hi": "जीवनकाल", "ar": "العمر", "pt": "LONGEVIDADE", "ru": "ДОЛГОВЕЧНОСТЬ", "ja": "寿命", "de": "LEBENSDAUER" }, "value": 16, "unit_i18n": { "fr": "ans", "en": "years", "es": "años", "zh": "年", "hi": "साल", "ar": "سنوات", "pt": "anos", "ru": "лет", "ja": "年", "de": "Jahre" } },
        "vitesse_sol": { "emoji": "🏃", "label": { "fr": "VITESSE (Sol)", "en": "SPEED (Land)", "es": "VELOCIDAD (Tierra)", "zh": "速度 (陆地)", "hi": "गति (भूमि)", "ar": "السرعة (أرض)", "pt": "VELOCIDADE (Terra)", "ru": "СКОРОСТЬ (Земля)", "ja": "速度 (陸)", "de": "GESCHW. (Land)" }, "value": 45, "unit": "km/h" },
        "vitesse_air": { "emoji": "🕊️", "label": { "fr": "VITESSE (Air)", "en": "SPEED (Air)", "es": "VELOCIDAD (Aire)", "zh": "速度 (空中)", "hi": "गति (वायु)", "ar": "السرعة (جو)", "pt": "VELOCIDADE (Ar)", "ru": "СКОРОСТЬ (Воздух)", "ja": "速度 (空)", "de": "GESCHW. (Luft)" }, "value": 0, "unit": "km/h" },
        "vitesse_eau": { "emoji": "🌊", "label": { "fr": "VITESSE (Eau)", "en": "SPEED (Water)", "es": "VELOCIDAD (Agua)", "zh": "速度 (水中)", "hi": "गति (जल)", "ar": "السرعة (ماء)", "pt": "VELOCIDADE (Água)", "ru": "СКОРОСТЬ (Вода)", "ja": "速度 (水)", "de": "GESCHW. (Wasser)" }, "value": 3, "unit": "km/h" }
    },
    "battle_history": { "taille": { "high_wins": 0, "high_losses": 0, "low_wins": 0, "low_losses": 0 }, "poids": { "high_wins": 0, "high_losses": 0, "low_wins": 0, "low_losses": 0 }, "longevite": { "high_wins": 0, "high_losses": 0, "low_wins": 0, "low_losses": 0 }, "vitesse_sol": { "high_wins": 0, "high_losses": 0, "low_wins": 0, "low_losses": 0 }, "vitesse_air": { "high_wins": 0, "high_losses": 0, "low_wins": 0, "low_losses": 0 }, "vitesse_eau": { "high_wins": 0, "high_losses": 0, "low_wins": 0, "low_losses": 0 } }
};

const provenanceData = {
    "hiveIdentity": { "hiveId": "kikko-genesis-hive-004", "kikkoVersion": "1.0.0", "deviceFingerprint": "pre-forged-in-dev-environment" },
    "pollenChronicle": [ { "timestamp": "2025-07-08T16:00:00Z", "pollenType": "WebCapture", "source": "AI-Overview", "reference": "https://www.google.com/search?q=chien+loup+tchecoslovaque..." } ],
    "hiveLog": [
        { 
            "timestamp": "2025-07-08T16:01:00Z", "agent": "AI_Queen_Gemma", "action": "Inference:GenerateQuiz",
            "output": {
                "quiz_data_i18n": {
                    "fr": [{"question": "Quel animal a été croisé avec un Berger Allemand pour créer cette race ?", "options": {"A": "Un renard", "B": "Un loup des Carpates", "C": "Un coyote", "D": "Un dingo"}, "answer": "B"}, {"question": "Quelle est l'espérance de vie moyenne de cette race ?", "options": {"A": "8-10 ans", "B": "10-12 ans", "C": "12-16 ans", "D": "16-18 ans"}, "answer": "C"}, {"question": "Quel est un des défis potentiels dans l'éducation de ce chien ?", "options": {"A": "Son manque d'intelligence", "B": "Son besoin excessif de câlins", "C": "Son instinct de prédation", "D": "Son besoin de rester seul"}, "answer": "C"}],
                    "en": [{"question": "What animal was crossed with a German Shepherd to create this breed?", "options": {"A": "A fox", "B": "A Carpathian wolf", "C": "A coyote", "D": "A dingo"}, "answer": "B"}, {"question": "What is the average life expectancy of this breed?", "options": {"A": "8-10 years", "B": "10-12 years", "C": "12-16 years", "D": "16-18 years"}, "answer": "C"}, {"question": "What is one of the potential challenges in training this dog?", "options": {"A": "Its lack of intelligence", "B": "Its excessive need for cuddles", "C": "Its predation instinct", "D": "Its need to be alone"}, "answer": "C"}]
                }
            }
        },
        { "timestamp": "2025-07-08T16:02:00Z", "agent": "Forager_Kurodo", "action": "UserValidation", "user_comment": "Carte de démarrage 'Inu' validée." },
        { "timestamp": "2025-07-08T16:03:00Z", "agent": "AI_Queen_Gemma", "action": "FinalizeMicrosite", "decision": "STATUS_TRUSTED_GENESIS" }
    ],
    "hornetLog": []
};